const countryOptions = {
  Europe: [
    "Belgium",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "Netherlands",
    "Switzerland",
    "United Kingdom",
  ],
  Africa: [
    "Nigeria",
    "Ethiopia",
    "Egypt",
    "South Africa",
    "Kenya",
    "Uganda",
    "Algeria",
    "Sudan",
  ],
  Asia: [
    "China",
    "India",
    "Japan",
    "South Korea",
    "Indonesia",
    "Saudi Arabia",
    "Iran",
    "Turkey",
  ],
  NorthAmerica: [
    "United States",
    "Canada",
    "Mexico",
    "Cuba",
    "Guatemala",
    "Honduras",
    "Nicaragua",
    "Costa Rica",
  ],
  SouthAmerica: [
    "Brazil",
    "Argentina",
    "Colombia",
    "Chile",
    "Peru",
    "Venezuela",
    "Ecuador",
    "Paraguay",
  ],
  Australia: [
    "Australia",
    "New Zealand",
    "Papua New Guinea",
    "Fiji",
    "Solomon Islands",
    "Vanuatu",
    "Samoa",
    "Tonga",
  ],
  Antarctica: [],
};

export default countryOptions;
